"""add feedback_sent to bookings

Revision ID: 167035c2b45e
Revises: f5eb9c99466a
Create Date: 2026-02-06 22:51:07.813501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '167035c2b45e'
down_revision: Union[str, None] = 'f5eb9c99466a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('feedback_sent', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'feedback_sent')
    # ### end Alembic commands ###
