"""add_salon_preparation_text

Revision ID: 2233db6e5177
Revises: 31b89ef5c9d0
Create Date: 2026-02-10 18:01:56.708437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2233db6e5177'
down_revision: Union[str, None] = '31b89ef5c9d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('salon_info', sa.Column('preparation_text', sa.Text(), server_default='', nullable=False))

    # Seed current Chocoo Skin preparation text into existing row
    chocoo_text = (
        "🔹 накануне вечером или утром (но не менее чем за 6 часов до процедуры) "
        "распарить кожу и проскрабировать все тело, можно использовать мочалку или скраб, "
        "но! обязательно без масел (сахар + гель для душа - отличный вариант; "
        "кофейные и соляные скрабы не используем), после этого не наносим крем на тело\n"
        "🔹 перед процедурой, если есть возможность, следует принять душ без геля, "
        "и не наносить крема и дезодорант\n"
        "🔹 одежда - темных цветов, свободная без перетягивающих элементов"
    )
    op.execute(
        sa.text("UPDATE salon_info SET preparation_text = :txt").bindparams(txt=chocoo_text)
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('salon_info', 'preparation_text')
    # ### end Alembic commands ###
