"""add_user_instagram

Revision ID: 31b89ef5c9d0
Revises: 167035c2b45e
Create Date: 2026-02-06 23:52:34.057007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31b89ef5c9d0'
down_revision: Union[str, None] = '167035c2b45e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('instagram', sa.String(length=60), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'instagram')
    # ### end Alembic commands ###
