"""initial schema

Revision ID: 40b188bfc485
Revises: 
Create Date: 2026-02-06 21:31:05.886999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40b188bfc485'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bookings', 'remind_before_hours',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('2'))
    op.alter_column('bookings', 'reminded',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.create_index('ix_booking_status_reminded', 'bookings', ['status', 'reminded'], unique=False)
    op.create_index(op.f('ix_bookings_client_id'), 'bookings', ['client_id'], unique=False)
    op.create_index(op.f('ix_bookings_status'), 'bookings', ['status'], unique=False)
    op.alter_column('salon_info', 'instagram',
               existing_type=sa.VARCHAR(length=500),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('services', 'short_description',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("''::text"))
    op.create_index('ix_slot_date_status', 'slots', ['date', 'status'], unique=False)
    op.create_unique_constraint('uq_slot_datetime', 'slots', ['date', 'start_time', 'end_time'])
    op.alter_column('users', 'consent_given',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'consent_given',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_constraint('uq_slot_datetime', 'slots', type_='unique')
    op.drop_index('ix_slot_date_status', table_name='slots')
    op.alter_column('services', 'short_description',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("''::text"))
    op.alter_column('salon_info', 'instagram',
               existing_type=sa.VARCHAR(length=500),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.drop_index(op.f('ix_bookings_status'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_client_id'), table_name='bookings')
    op.drop_index('ix_booking_status_reminded', table_name='bookings')
    op.alter_column('bookings', 'reminded',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('bookings', 'remind_before_hours',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('2'))
    # ### end Alembic commands ###
